# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 2700s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20260108-7f313c340e@sha256:4d778a001ae3f4247b2b61d8a870319e71d66c87556969a6399b90972e4d0491'
    entrypoint: make
    env:
    - TAG=$_PULL_BASE_REF
    - GIT_COMMIT=$_PULL_BASE_SHA
    args:
    - push
